name: Monitor Lovable Status

on:
  schedule:
    # Run every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  check-status:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run status monitor
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
        ONLY_ACTIVE_INCIDENTS: true
        CHECK_INTERVAL_MINUTES: 0  # Run once per workflow
      run: |
        # Create a temporary script to run once
        cat > run_once.py << 'EOF'
        import asyncio
        import sys
        import os
        sys.path.insert(0, os.path.dirname(__file__))
        from main import StatusBot
        
        async def run_once():
            bot = StatusBot()
            await bot.fetch_and_process_feed()
            
        asyncio.run(run_once())
        EOF
        
        python run_once.py
    
    - name: Commit database changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Check if database file exists and has changes
        if [ -f lovable_status.db ]; then
          git add lovable_status.db
          git diff --staged --quiet || git commit -m "Update incident database [skip ci]"
        fi
    
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}